Lu 9
archan96/lumia-ui pull request #11
Opened 2024-04-12 09:40 UTC by sanketXynes

Checkbox

2024-04-13 01:50 UTC, archan96 requested changes
Please make the following changes and push @sanketXynes

2024-04-13 01:50 UTC, archan96 commented on src/components/TextInput/textInput.type.ts
> +  type?: "fill" | "outlined" | "outline-only" | "-M";
Why this -M?

2024-04-13 01:50 UTC, archan96 commented on src/components/TextInput/textInput.tsx
> +    background-color: ${type !== "outline-only"
make this bit efficient

2024-04-13 01:50 UTC, archan96 commented on src/components/Checkbox/checkbox.tsx
> +    background-color: ${color?.skyblue1};
This is brand100 in other places.

2024-04-13 01:50 UTC, archan96 commented on src/components/TextInput/textInput.tsx
> +            //   style={iconAtEnd ? { marginLeft: "0.5vw" } : { marginRight: "0.5vw" }}
Remove unused comments

2024-04-13 01:50 UTC, archan96 commented on src/components/TextInput/textInput.type.ts
> +// import { AssetProps } from "@icons/types/asset.types";
remove unused comments

2024-04-15 11:04 UTC, archan96 approved these changes
Cool

2024-04-15 11:04 UTC, archan96 commented on src/components/Checkbox/checkbox.type.ts
> +  isChecked?: boolean;
It needs a callback onUpdate

2024-04-15 12:35 UTC, archan96 approved these changes
Cool

2024-04-15 12:35 UTC, archan96 approved these changes
All changes are fine.

2024-04-15 12:38 UTC, xynes-admin approved these changes
All changes are approved.

2024-04-15 12:42 UTC, archan96 approved these changes
Approved resolved conflicts

2024-04-15 12:42 UTC, merged