LU-18 input all updated
archan96/lumia-ui pull request #14
Opened 2024-04-13 01:29 UTC by archan96

2024-04-13 10:12 UTC, sanketXynes requested changes
Please resolve

2024-04-13 10:12 UTC, sanketXynes commented on src/components/Inputs/PinInput/components/pinInputField.tsx
> +    width: 40px; /* Adjust width as needed */
Static values should be in the css file

2024-04-13 10:12 UTC, sanketXynes commented on src/components/Inputs/PinInput/components/pinInputField.tsx
> +    width: 40px; /* Adjust width as needed */
Should use vh, vw instade of px

2024-04-14 08:15 UTC, xynes-admin commented on src/components/Inputs/PinInput/components/pinInputField.tsx
> +    width: 40px; /* Adjust width as needed */
Resolved in the new commit.

2024-04-14 08:15 UTC, xynes-admin commented on src/components/Inputs/PinInput/components/pinInputField.tsx
> +    width: 40px; /* Adjust width as needed */
Resolved in the latest commit.

2024-04-15 08:25 UTC, sanketXynes approved these changes
Approved

2024-04-15 09:58 UTC, merged