Lu 26/dialouge
archan96/lumia-ui pull request #35
Opened 2024-05-01 12:24 UTC by Aman9804

Please review and approve

2024-05-02 12:02 UTC, sanketXynes approved these changes
Approved

2024-05-03 12:36 UTC, archan96 requested changes
Make the following changes

2024-05-03 12:36 UTC, archan96 commented on src/components/Dialouge/dialouge.tsx
> +    const StyledDialouge = styled(BasicStyledDialouge)`
Move these three to styles.ts

2024-05-03 12:36 UTC, archan96 commented on src/components/Dialouge/dialouge.type.tsx
> +    visible: boolean;
Make this optional

2024-05-06 08:43 UTC, Aman9804 commented
Changes made

2024-05-06 08:44 UTC, Aman9804 commented on src/components/Dialouge/dialouge.type.tsx
> +    visible: boolean;
Done

2024-05-06 08:44 UTC, Aman9804 commented on src/components/Dialouge/dialouge.tsx
> +    const StyledDialouge = styled(BasicStyledDialouge)`
Done

2024-05-06 09:00 UTC, archan96 approved these changes
Sounds good

2024-05-06 09:01 UTC, archan96 approved these changes
All things looks good

2024-05-06 09:02 UTC, xynes-admin approved these changes
All things are fine

2024-05-08 05:15 UTC, sanketXynes approved these changes
Approved

2024-05-08 05:16 UTC, merged