fix given
archan96/lumia-ui pull request #49
Opened 2024-05-16 05:22 UTC by sanketXynes

1. Indeterminate state added
2. isChecked removed, onUpdate fixed.
3. Behavior of checkbox fixed

2024-05-27 08:36 UTC, archan96 requested changes
@sanketXynes please make the changes

2024-05-27 08:36 UTC, archan96 commented on src/components/Checkbox/checkbox.stories.ts
> +      console.log("The val------", e);
Remove logs

2024-05-28 06:31 UTC, Aman9804 approved these changes
approved

2024-06-01 09:07 UTC, archan96 approved these changes
Looks good.

2024-06-01 09:11 UTC, xynes-admin approved these changes
Looks good

2024-06-01 09:12 UTC, merged